### ISSUE TITLE
Power mark fails with extra punctuation attached

### ISSUE THREAD

**Issue by hftf** [alopezlago/MODAQ#282]
I don't have the packet to actually check my hypothesis since I wasn't reading that round and earlier packets were deleted from the packet-sharing thread throughout the day for some reason, but fairly certain I saw a `(*),` in the question out of the corner of my eye when we had a problem in which a buzz before that token was only counted for 10 points. Possible culprit line:

https://github.com/alopezlago/MODAQ/blob/a2f429856550951467e86021e1b4629aeea7b715/src/state/PacketState.ts#L132

**Comment by alopezlago** [comment]
I think it's a bit earlier on this line.: https://github.com/alopezlago/MODAQ/blob/a2f429856550951467e86021e1b4629aeea7b715/src/state/PacketState.ts#L79

But we have to fix both spots

**Comment by alopezlago** [comment]
Should be fixed in the next verison.

**Comment by alopezlago** [comment]
This wasn't fixed; the branch with the fix is on hold for now, but I'll try porting this fix to the next improvement.

**Comment by hftf** [comment]
Reopening — issue still exists when a word is unintentionally attached to the `(*)`, e.g. `dub(*)` (no space).

Found out that it can actually be resolved ad-hoc by adding an extra comma-separated powermark in the options, e.g. `dub(*),(*)` and setting the point value to `15,15`.
